# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C\:\\Program Files\\OpenLogic\\jdk-21.0.8.9-hotspot
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.20.4
yarn_mappings=1.20.4+build.1
loader_version=0.15.11
# Mod Properties
mod_version=v1.28
maven_group=org.example.changeofcontrol
archives_base_name=change-of-control
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.97.2+1.20.4
